services:
  ppo_agent:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime         
 
    image: ppo-libtorch-cxx   
 
    volumes:
      - ./output:/app/output
 
    environment:
      - PYTHONUNBUFFERED=1    
 
    stdin_open: true
    tty: true